/**
 *
 */
package com.force.formula.impl;

import java.util.LinkedList;
import java.util.List;

/**
 * JEST Data Model POJO class.
 * This class will represent JSON object which is going to be generated by BaseFormulaGenericTests.java
 * This json will be consumed by JSON tests
 * @author jkathiara
 */
public class JestDataModel {

	public String testSuiteName;
	public String formula;
	public String returnType;
	public int precision;
	public int scale;
	public List<JSCode> jsCodes;
	public List<TestData> tests;

	public JestDataModel() {
		jsCodes = new LinkedList<JSCode>();
		tests = new LinkedList<TestData>();
	}

}
